version: 2.1

orbs:
  docker: circleci/docker@2.5.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: cinematrix
      DOCKER_TAG: latest
      SPRING_PROFILES_ACTIVE: prod
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      #git pull
      - checkout
      - setup_remote_docker
      - run:
          name: maven package
          command: |
            chmod +x mvnw
            sed -i "s/\r$//" mvnw
            ./mvnw --version
            ./mvnw clean install -P release
      - run:
          name: build-push-docker-image
          command: |
            echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG .
            docker images
            docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
  deploy:
    environment:
      DOCKER_IMAGE: cinematrix
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - run:
          name: create docker-compose file
          command: |
            cat \<<EOF > docker-compose.yaml 
            version: '3.8'
            services:
              cinematrix:
                image: $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
                ports:
                  - "443:443"
            EOF
            cat \<<EOF > deploy.sh
            docker-compose stop
            docker-compose rm -f
            docker-compose pull
            docker-compose up -d
            EOF
      - add_ssh_keys:
          fingerprints:
            - $FINGER_PRINT
      - run:
          name: copy-file-to-remote-server
          command: |
            chmod +x deploy.sh
            scp -oStrictHostKeyChecking=no deploy.sh $DEPLOY_USER@$DEPLOY_SERVER:~/
            scp docker-compose.yaml $DEPLOY_USER@$DEPLOY_SERVER:~/
      - run: ssh -v $DEPLOY_USER@$DEPLOY_SERVER './deploy.sh'

workflows:
  my-workflow:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - dev
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only:
                - dev

# by bourbon zz